-- 去掉所有表的 AUTO_INCREMENT，改用 MyBatis-Plus 雪花算法生成 ID
ALTER TABLE project MODIFY id BIGINT NOT NULL;
ALTER TABLE conversation MODIFY id BIGINT NOT NULL;
ALTER TABLE generation MODIFY id BIGINT NOT NULL;
ALTER TABLE deployment MODIFY id BIGINT NOT NULL;
ALTER TABLE system_config MODIFY id BIGINT NOT NULL;
ALTER TABLE chat_thread MODIFY id BIGINT NOT NULL;
