-- 补全所有表的列中文注释（V7 修改 id 列时丢失了 COMMENT，created_at/updated_at 也缺失）

-- ========== project 表 ==========
ALTER TABLE project MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID';
ALTER TABLE project MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE project MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ========== conversation 表 ==========
ALTER TABLE conversation MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID';
ALTER TABLE conversation MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== generation 表 ==========
ALTER TABLE generation MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID';
ALTER TABLE generation MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== deployment 表 ==========
ALTER TABLE deployment MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID';
ALTER TABLE deployment MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== system_config 表 ==========
ALTER TABLE system_config MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID';
ALTER TABLE system_config MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE system_config MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ========== chat_thread 表 ==========
ALTER TABLE chat_thread MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID';
ALTER TABLE chat_thread MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE chat_thread MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
