# 使用说明 4.0 - 微服务架构版本
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动
services:
  ai-work-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: ai-work-mysql
    image: ai-work-mysql
    command: --lower_case_table_names=1
    ports:
      - 3306:3306
    networks:
      - spring_cloud_default

  ai-work-redis:
    container_name: ai-work-redis
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/redis
    restart: always
    networks:
      - spring_cloud_default

  ai-work-register:
    build:
      context: ./ai-work-register
    restart: always
    container_name: ai-work-register
    image: ai-work-register
    ports:
      - 8848:8848
      - 9848:9848
      - 18080:18080
    networks:
      - spring_cloud_default

  ai-work-gateway:
    build:
      context: ./ai-work-gateway
    restart: always
    container_name: ai-work-gateway
    image: ai-work-gateway
    ports:
      - 9999:9999
    networks:
      - spring_cloud_default

  ai-work-auth:
    build:
      context: ./ai-work-auth
    restart: always
    container_name: ai-work-auth
    image: ai-work-auth
    networks:
      - spring_cloud_default

  ai-work-upms:
    build:
      context: ./ai-work-upms/ai-work-upms-biz
    restart: always
    container_name: ai-work-upms
    image: ai-work-upms
    networks:
      - spring_cloud_default

  ai-work-monitor:
    build:
      context: ./ai-work-visual/ai-work-monitor
    restart: always
    image: ai-work-monitor
    container_name: ai-work-monitor
    ports:
      - 5001:5001
    networks:
      - spring_cloud_default

  ai-work-quartz:
    build:
      context: ./ai-work-visual/ai-work-quartz
    restart: always
    image: ai-work-quartz
    container_name: ai-work-quartz
    networks:
      - spring_cloud_default

  ai-work-codegen:
    build:
      context: ./ai-work-visual/ai-work-codegen
    restart: always
    image: ai-work-codegen
    container_name: ai-work-codegen
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name: spring_cloud_default
    driver: bridge
