FROM registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/java:21-anolis

MAINTAINER wangiegie@gmail.com

ENV TZ=Asia/Shanghai
ENV LANG C.UTF-8
ENV JAVA_OPTS="-Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom"

RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir -p /ai-work-quartz

WORKDIR /ai-work-quartz

EXPOSE 5007

ADD ./target/ai-work-quartz.jar ./

CMD sleep 30;java $JAVA_OPTS -jar ai-work-quartz.jar
